/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Check backend health */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/jobs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List seeded jobs */
        get: operations["listJobs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create an interview session for a job */
        post: operations["createSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/start": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start an interview and get the first question */
        post: operations["startSession"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit a candidate answer and receive the next question or terminal state */
        post: operations["submitTurn"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Resume or inspect a persisted session */
        get: operations["getSessionState"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/end-early": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End an interview before all competencies are covered */
        post: operations["endSessionEarly"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/evaluation": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get transcript and structured evaluation */
        get: operations["getEvaluation"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/sessions/{sessionId}/replay": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get replay data for a completed session */
        get: operations["getReplay"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/history": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List owner-scoped interview history */
        get: operations["getHistory"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            /** @example ok */
            status: string;
        };
        Job: {
            /** Format: uuid */
            id: string;
            title: string;
            description: string;
            competencyCount: number;
        };
        JobDetail: components["schemas"]["Job"];
        Session: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            jobId: string;
            status: components["schemas"]["SessionStatus"];
            completionReason?: components["schemas"]["CompletionReason"] | null;
            /** Format: date-time */
            startedAt?: string;
            /** Format: date-time */
            completedAt?: string | null;
        };
        /** @enum {string} */
        SessionStatus: "in_progress" | "completed" | "ended_early";
        /** @enum {string} */
        CompletionReason: "all_competencies_covered" | "question_cap" | "ended_early";
        /** @enum {string} */
        CompetencyCategory: "behavioral" | "technical";
        CompetencyStatus: {
            /** Format: uuid */
            id: string;
            name: string;
            category: components["schemas"]["CompetencyCategory"];
            /** @enum {string} */
            status: "not-reached" | "in-progress" | "covered";
        };
        CompetencyRef: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        Flag: {
            /** @enum {string} */
            flag: "vague_claim" | "no_evidence" | "interesting_thread" | "contradiction" | "well_covered" | "tradeoff_mentioned" | "metric_mentioned" | "specific_tool_mentioned";
            detail: string;
            /** Format: uuid */
            competencyId?: string | null;
            /** Format: uuid */
            triggerTurnId?: string | null;
            answerExcerpt?: string | null;
        };
        RubricCompetencySnapshot: {
            /** Format: uuid */
            id: string;
            /** @enum {string} */
            status: "covered" | "in-progress" | "not-reached";
            category?: components["schemas"]["CompetencyCategory"];
            evidenceTurnIds?: string[];
            followUpCount?: number;
            signalSummary?: string | null;
        };
        RubricSnapshot: {
            covered: string[];
            inProgress: string[];
            gaps: string[];
            competencies?: components["schemas"]["RubricCompetencySnapshot"][];
        };
        PolicyState: {
            questionCount: number;
            followUpCount: number;
            /** @example 6 */
            minQuestions: number;
            /** @example 2 */
            minFollowUps: number;
            /** @example 12 */
            maxQuestions: number;
            /** @example 2 */
            maxFollowUpsPerCompetency: number;
            followUpCountsByCompetency?: {
                [key: string]: number;
            };
            eligibleToEnd: boolean;
        };
        Trigger: {
            /** Format: uuid */
            turnId: string;
            answerExcerpt: string;
            reason: string;
        };
        Generation: {
            /** @enum {string} */
            mode: "pack_seed" | "targeted_follow_up" | "generic_probe" | "terminal";
            fallbackMode?: string | null;
            answerDependencyRequired: boolean;
        };
        /** @enum {string} */
        PolicyAction: "new_topic" | "follow_up" | "end";
        PanelState: {
            rubricSnapshot: components["schemas"]["RubricSnapshot"];
            flags: components["schemas"]["Flag"][];
            policyState: components["schemas"]["PolicyState"];
            action: components["schemas"]["PolicyAction"];
            /** Format: uuid */
            targetCompetencyId: string | null;
            /** Format: uuid */
            sourcePackItemId: string | null;
            trigger: components["schemas"]["Trigger"] | null;
            rationale: string;
            generation: components["schemas"]["Generation"];
            failureMode: string | null;
        };
        TerminalPanelState: components["schemas"]["PanelState"] & {
            completionReason: components["schemas"]["CompletionReason"];
            /** @enum {string} */
            endedBy: "controller" | "user";
            uncoveredCompetencyIds: string[];
        };
        Turn: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            clientTurnId?: string | null;
            /** @enum {string} */
            role: "interviewer" | "candidate";
            turnIndex: number;
            /** Format: uuid */
            competencyId: string;
            content: string;
            inputMode?: ("voice" | "text") | null;
            audioDurationMs?: number | null;
            action?: components["schemas"]["PolicyAction"] | null;
            /** Format: uuid */
            sourcePackItemId?: string | null;
            /** @description API-assembled panel state for replay/detail responses. The database stores `turns.reasoning` JSONB plus authoritative relational columns (`action`, `competency_id`, `source_pack_item_id`). */
            reasoning?: components["schemas"]["PanelState"] | null;
        };
        CreateSessionRequest: {
            /** Format: uuid */
            jobId: string;
        };
        StartSessionResponse: {
            question: string;
            turnIndex: number;
            panelState: components["schemas"]["PanelState"];
            competencies: components["schemas"]["CompetencyStatus"][];
            turns: components["schemas"]["Turn"][];
            jobTitle: string;
        };
        SubmitAnswerRequest: {
            /** Format: uuid */
            clientTurnId: string;
            answerText: string;
            /** @enum {string} */
            inputMode: "voice" | "text";
            audioDurationMs?: number | null;
        };
        SubmitAnswerResponse: {
            question: string | null;
            turnIndex: number;
            panelState: components["schemas"]["PanelState"];
            competencies: components["schemas"]["CompetencyStatus"][];
            turns: components["schemas"]["Turn"][];
            jobTitle: string;
            isComplete: boolean;
            terminalPanelState: components["schemas"]["TerminalPanelState"] | null;
            evaluationReady: boolean;
        };
        SessionStateResponse: {
            session: components["schemas"]["Session"];
            turns: components["schemas"]["Turn"][];
            panelState: components["schemas"]["PanelState"];
            competencies: components["schemas"]["CompetencyStatus"][];
            jobTitle: string;
            currentQuestion: string | null;
            turnIndex: number;
            status: components["schemas"]["SessionStatus"];
            /** @description True when the latest persisted turn is a candidate answer with no following interviewer turn. */
            needsRecovery: boolean;
            terminalPanelState: components["schemas"]["TerminalPanelState"] | null;
        };
        EndSessionEarlyResponse: {
            uncoveredCompetencies: components["schemas"]["CompetencyRef"][];
            terminalPanelState: components["schemas"]["TerminalPanelState"];
            evaluationReady: boolean;
        };
        ScoreScale: {
            /** @example 1 */
            min: number;
            /** @example 10 */
            max: number;
        };
        /** @description Validated evidence JSONB payload from session_competency_scores.evidence. */
        CompetencyEvidence: {
            /** @example competency_evidence.v1 */
            schemaVersion: string;
            /** @example v1 */
            evaluationVersion: string;
            coverage: {
                probed: boolean;
                assessed: boolean;
                /** Format: uuid */
                firstQuestionTurnId: string | null;
                questionTurnIds: string[];
                answerTurnIds: string[];
            };
            supportingTurnIds: string[];
            quotes: {
                /** Format: uuid */
                turnId: string;
                quote: string;
                /** @enum {string} */
                type: "strength" | "concern" | "neutral";
                note: string;
            }[];
            signals: {
                /** Format: uuid */
                turnId: string;
                flag: string;
                detail: string;
            }[];
            scoreRationale: string | null;
            unassessedReason: string | null;
        };
        CompetencyScore: {
            /** Format: uuid */
            competencyId: string;
            name: string;
            category: components["schemas"]["CompetencyCategory"];
            assessed: boolean;
            score: number | null;
            notes: string | null;
            evidence: components["schemas"]["CompetencyEvidence"] | null;
        };
        /** @description Public evaluation narrative. Score scale is exposed on Evaluation.scoreScale; internal model provenance is not exposed directly. */
        EvaluationNarrative: {
            summary: string;
            /** @enum {string} */
            overallVerdict: "strong" | "mixed" | "needs_improvement" | "insufficient_signal";
            strengths: {
                /** Format: uuid */
                competencyId: string;
                text: string;
                turnIds: string[];
            }[];
            concerns: {
                /** Format: uuid */
                competencyId: string;
                text: string;
                turnIds: string[];
            }[];
            unassessedCompetencyIds: string[];
            earlyEndNote: string | null;
            modelFailureNote: string | null;
        };
        Evaluation: {
            overallScore: number | null;
            scoreScale: components["schemas"]["ScoreScale"];
            competencyScores: components["schemas"]["CompetencyScore"][];
            narrative: components["schemas"]["EvaluationNarrative"];
        };
        SessionDetail: {
            session: components["schemas"]["Session"];
            job: components["schemas"]["JobDetail"];
            competencies: components["schemas"]["CompetencyStatus"][];
            turns: components["schemas"]["Turn"][];
            evaluation: components["schemas"]["Evaluation"] | null;
            terminalPanelState: components["schemas"]["TerminalPanelState"] | null;
        };
        SessionSummary: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            jobId: string;
            jobTitle: string;
            status: components["schemas"]["SessionStatus"];
            /** Format: date-time */
            startedAt: string;
            /** Format: date-time */
            completedAt: string | null;
            durationMs: number | null;
            overallScore: number | null;
            coveragePercent: number | null;
            talkRatio: number | null;
            questionCount: number;
            followUpCount: number;
        };
        HistoryResponse: {
            sessions: components["schemas"]["SessionSummary"][];
        };
        ErrorResponse: {
            error: {
                /** @enum {string} */
                code: "invalid_owner_id" | "job_not_found" | "session_not_found" | "session_not_in_progress" | "session_in_progress" | "turn_already_submitted" | "validation_error" | "model_unavailable" | "catalog_setup_error";
                message: string;
                details?: {
                    [key: string]: unknown;
                };
                requestId?: string | null;
            };
        };
    };
    responses: {
        /** @description Standard error response */
        ErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        SessionId: string;
        OwnerIdHeader: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Backend is reachable */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Bad request */
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    listJobs: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Job list */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        jobs: components["schemas"]["Job"][];
                    };
                };
            };
            /** @description Bad request */
            400: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    createSession: {
        parameters: {
            query?: never;
            header: {
                "X-Owner-Id": components["parameters"]["OwnerIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateSessionRequest"];
            };
        };
        responses: {
            /** @description Session created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Session"];
                };
            };
            /** @description Invalid owner ID header */
            400: components["responses"]["ErrorResponse"];
            /** @description Job not found */
            404: components["responses"]["ErrorResponse"];
            /** @description Request validation error */
            422: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    startSession: {
        parameters: {
            query?: never;
            header: {
                "X-Owner-Id": components["parameters"]["OwnerIdHeader"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description First question and panel state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartSessionResponse"];
                };
            };
            /** @description Invalid owner ID header */
            400: components["responses"]["ErrorResponse"];
            /** @description Session not found */
            404: components["responses"]["ErrorResponse"];
            /** @description Session not startable */
            409: components["responses"]["ErrorResponse"];
            /** @description Invalid UUID path parameter */
            422: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    submitTurn: {
        parameters: {
            query?: never;
            header: {
                "X-Owner-Id": components["parameters"]["OwnerIdHeader"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description Next interview turn or completed interview state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitAnswerResponse"];
                };
            };
            /** @description Invalid owner ID header */
            400: components["responses"]["ErrorResponse"];
            /** @description Session not found */
            404: components["responses"]["ErrorResponse"];
            /** @description Session lifecycle conflict or duplicate turn */
            409: components["responses"]["ErrorResponse"];
            /** @description Request validation error */
            422: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    getSessionState: {
        parameters: {
            query?: never;
            header: {
                "X-Owner-Id": components["parameters"]["OwnerIdHeader"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Persisted session state */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStateResponse"];
                };
            };
            /** @description Invalid owner ID header */
            400: components["responses"]["ErrorResponse"];
            /** @description Session not found */
            404: components["responses"]["ErrorResponse"];
            /** @description Invalid UUID path parameter */
            422: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    endSessionEarly: {
        parameters: {
            query?: never;
            header: {
                "X-Owner-Id": components["parameters"]["OwnerIdHeader"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Terminal panel state and uncovered competencies */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndSessionEarlyResponse"];
                };
            };
            /** @description Invalid owner ID header */
            400: components["responses"]["ErrorResponse"];
            /** @description Session not found */
            404: components["responses"]["ErrorResponse"];
            /** @description Session not in progress */
            409: components["responses"]["ErrorResponse"];
            /** @description Invalid UUID path parameter */
            422: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    getEvaluation: {
        parameters: {
            query?: never;
            header: {
                "X-Owner-Id": components["parameters"]["OwnerIdHeader"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session detail with evaluation */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Invalid owner ID header */
            400: components["responses"]["ErrorResponse"];
            /** @description Session not found */
            404: components["responses"]["ErrorResponse"];
            /** @description Session still in progress */
            409: components["responses"]["ErrorResponse"];
            /** @description Invalid UUID path parameter */
            422: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    getReplay: {
        parameters: {
            query?: never;
            header: {
                "X-Owner-Id": components["parameters"]["OwnerIdHeader"];
            };
            path: {
                sessionId: components["parameters"]["SessionId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Replay detail */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionDetail"];
                };
            };
            /** @description Invalid owner ID header */
            400: components["responses"]["ErrorResponse"];
            /** @description Session not found */
            404: components["responses"]["ErrorResponse"];
            /** @description Session still in progress */
            409: components["responses"]["ErrorResponse"];
            /** @description Invalid UUID path parameter */
            422: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
    getHistory: {
        parameters: {
            query?: {
                jobId?: string;
            };
            header: {
                "X-Owner-Id": components["parameters"]["OwnerIdHeader"];
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Session summaries */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HistoryResponse"];
                };
            };
            /** @description Invalid owner ID header */
            400: components["responses"]["ErrorResponse"];
            /** @description Invalid optional jobId query parameter */
            422: components["responses"]["ErrorResponse"];
            default: components["responses"]["ErrorResponse"];
        };
    };
}
